### ISSUE TITLE
Problem when trying to add a third section to wing

### ISSUE THREAD

**Issue by ManoelFylipe** [nikhil-sethi/xflrpy#5]
When trying to create a wing with three sections the xfflrpy client crashes, even when creating a plane within the xflrpy CLI, and opening it with the API, when I try to just save with a different name the three sections wihg the xflrtpy crashes.

**Comment by AlexAnderssonChalmers** [comment]
Is there a solution to this? I got the same issue.

**Comment by nikhil-sethi** [comment]
Hey @ManoelFylipe, thanks a lot for raising this issue. Apologies for the late response, I've been under hibernation. 
It should be fixed now with commit https://github.com/nikhil-sethi/xflrpy/commit/f6db4902dafe8c0323de0ff342227c3d2527a59b.

**Comment by AlexAnderssonChalmers** [comment]
Tried it out, still crashes when a third section is added. Each time with a "Retry connection over the limit" error.
